[tool.black]
line-length = 100
target-version = ["py312"]
extend-exclude = "(venv312|\\.venv|reports|__pycache__)"

[tool.isort]
profile = "black"
line_length = 100
skip = ["venv312", ".venv", "reports", "__pycache__"]
